#!/usr/bin/env python3
import subprocess

print("running pre-push")

# Ruy a few things for the "rust_by_example" project;
# * cargo clippy
# * cargo test
def rust_by_example(file_changed):
    should_run = any(file_changed.startswith("rust_by_example") for file_changed in files_changed)
    if should_run:
        print("Going to run 'cargo clippy' for rust_by_example.")
        subprocess.check_call(
            "cd rust_by_example; env RUSTFLAGS=-Dwarnings cargo clippy",
            shell=True)
        print("Going to run 'cargo test' for rust_by_example.")
        subprocess.check_call(
            "cd rust_by_example; env RUSTFLAGS=-Dwarnings cargo test",
            shell=True)

output = subprocess.getoutput("git diff origin/master...HEAD --name-only")
files_changed = output.split("\n")
rust_by_example(files_changed)
