/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jduan

import com.google.inject.Guice

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val injector = Guice.createInjector(DemoModule())
    val greeter = injector.getInstance(Greeter::class.java)
    greeter.sayHello()
}
