#!/usr/bin/env bash
# This script searches something across all major repos
# eg: cs setup-java

repos_root=$HOME/repos/
repos=(api-platform bayone devops infra release)

for repo in "${repos[@]}"
do
  echo "------------------- $repo ----------------"
  cd "$repos_root/worktrees/$repo"
  # git fetch > /dev/null 2>&1
  git checkout origin/main > /dev/null 2>&1
  rg "$@" "$repos_root/worktrees/$repo"
  printf "\n\n\n"
done
