#!/usr/bin/env bash
# This script searches files by name across all major repos
# eg: fd setup-java
set -euo pipefail

repos_root=$HOME/repos/
repos=(api-platform bayone devops infra release)
shift

for repo in "${repos[@]}"
do
  echo "------------------- $repo ----------------"
  cd "$repos_root/worktrees/$repo"
  # git fetch > /dev/null 2>&1
  git checkout origin/main
  fd "$@" "$repos_root/worktrees/$repo"
  printf "\n\n\n"
done
