load(":bazel/archive.bzl", "archive")

archive(
    name="documentation",
    files=[
        "src/README.md",
    ],
)

archive(
    name="release",
    files=[
        "src/RELEASE.md",
    ],
)

archive(
    name="all",
    files=[
        "src/README.md",
        "src/RELEASE.md",
    ],
)
