# Load the "http_archive" rule
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.2"

RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

# use "http_archive" to fetch a remote bazel project archive
http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" %
          RULES_JVM_EXTERNAL_TAG,
)

# load the "maven_install" rule from the "rules_jvm_external" bazel project
load("@rules_jvm_external//:defs.bzl", "maven_install")

# use the "maven_install" rule to download external dependencies
# this creates another external workspace called "@maven"
maven_install(
    artifacts = [
        "org.apache.commons:commons-compress:1.20",
        "commons-io:commons-io:2.7",
        "org.tukaani:xz:1.8",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
