load("@rules_python//python:defs.bzl", "py_binary")
load("@pip_deps//:requirements.bzl", "requirement")

py_binary(
    name = "sandbox",
    srcs = ["sandbox.py"],
    # deps = [
    #     "//:lib",
    # ]
)

py_binary(
    name = "parse_ipv4_address",
    srcs = ["parse_ipv4_address.py"],
    # deps = [
    #     "//:lib",
    # ]
)
