package(default_visibility = ["//visibility:public"])
load("//bazel:main.bzl", "java_package")

java_package(
    name = "package2",
    package = "com.jduan.package2",
    deps = [
        "@maven//:com_google_guava_guava",
    ]
)
