name: run-maven-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1
      - run: ./.github/scripts/run_maven_tests.sh
